networks:
  logistics-network:
    external: true
    
volumes:
  rabbitmq_data:
  redis_data:

services:
  logistics-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: logistics-rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - logistics-network

  logistics-redis:
    image: redis:7-alpine
    container_name: logistics-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - logistics-network

  logistics-zipkin-server:
    image: openzipkin/zipkin:latest
    container_name: logistics-zipkin-server
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9411/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - logistics-network