include:
  - docker-compose.infra.yml
  - docker-compose.config.yml
  - docker-compose.discovery.yml
  - docker-compose.gateway.yml
  - docker-compose.notification.yml
  - docker-compose.hub.yml
  - docker-compose.user.yml
  - docker-compose.auth.yml
  - docker-compose.delivery.yml
  - docker-compose.company-product.yml
  - docker-compose.order.yml
